spring:
  application:
    name: api-gateway
  config:
    import: configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-product
          uri: http://localhost:9999
          predicates:
            - Path=/products/**
          filters:
            - name: CircuitBreaker
              args:
                name: productServiceCircuitBreaker
                fallbackUri: forward:/fallback/productServiceFallBack
            - RewritePath=/products/?(?<segment>.*), /${segment}

        - id: ms-order
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**
          filters:
            - name: CircuitBreaker
              args:
                name: orderServiceCircuitBreaker
                fallbackUri: forward:/fallback/orderServiceFallBack
            - RewritePath=/orders/?(?<segment>.*), /${segment}

        - id: ms-payment
          uri: http://localhost:8082
          predicates:
            - Path=/payments/**
          filters:
            - name: CircuitBreaker
              args:
                name: paymentServiceCircuitBreaker
                fallbackUri: forward:/fallback/paymentServiceFallBack
            - RewritePath=/payments/?(?<segment>.*), /${segment}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0

springdoc:
  swagger-ui:
    urls:
      - name: ms-product
        url: http://localhost:9999/v3/api-docs
      - name: ms-order
        url: http://localhost:8081/v3/api-docs
      - name: ms-payment
        url: http://localhost:8082/v3/api-docs

server:
  port: 9090

